name:                AllForTops
version:             0.1.0.0
github:              "cspollard/AllForTops"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cpollard@cern.ch"
copyright:           "2018 Chris Pollard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AllForTops#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  AllForTops-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      # - -threaded
    - -rtsopts
      # - -with-rtsopts=-N
    - -Wall
    dependencies:
    - AllForTops
    - atlas
    - ttree
    - foldl
    - pipes
    - lens
    - mtl
    - histogram-fill
    - comonad
    - vector
    - histogram-extras
    - transformers
    - MonadRandom
    - text
    - containers
    - optparse-generic
